---
- hosts: masters
  tasks:
  - name: Set identity providers
    yedit:  
      src: /etc/origin/master/master-config.yaml
      key: oauth#identityProviders
      value:
        identityProviders:
        - challenge: true
          login: true
          mappingMethod: claim
          name: anypassword
          provider:
            apiVersion: v1
            kind: HTPasswdIdentityProvider
            file: /var/lib/openshift/config/master/htpasswd
            
  handlers:
  - name: Restart OpenShift
    service:
      name: openshift
      state: restarted

